services:
  - type: web
    name: backend
    runtime: docker
    plan: free
    region: ohio
    dockerContext: ./apps/backend
    dockerfilePath: ./apps/backend/Dockerfile.multistage
    envVars:
      - key: APP_MY_SECRET
        sync: false
      - key: APP_API_HOST
        value: 0.0.0.0
      - key: APP_API_PORT
        value: 8000
      - key: APP_RENDER_FRONTEND_HOST
        fromService:
          type: web
          name: frontend
          property: host
      - key: POSTGRESQL_DRIVER
        value: postgresql+asyncpg
      - key: POSTGRESQL_USERNAME
        fromDatabase:
          name: invoice_automator_db
          property: user
      - key: POSTGRESQL_PASSWORD
        fromDatabase:
          name: invoice_automator_db
          property: password
      - key: POSTGRESQL_HOST
        fromDatabase:
          name: invoice_automator_db
          property: host
      - key: POSTGRESQL_PORT
        fromDatabase:
          name: invoice_automator_db
          property: port
      - key: POSTGRESQL_DATABASE
        fromDatabase:
          name: invoice_automator_db
          property: database

  - type: web
    name: frontend
    runtime: docker
    plan: free
    dockerContext: ./apps/frontend
    dockerfilePath: ./apps/frontend/Dockerfile.multistage
    envVars:
      - key: VITE_RENDER_BACKEND_HOST
        fromService:
          type: web
          name: backend
          property: host

databases:
  - name: invoice_automator_db
    databaseName: invoice_automator_db
    user: invoice_automator_user
    plan: free
    region: ohio
